theme = "solarized_dark"

[editor]
mouse = true
middle-click-paste = false
scroll-lines = 1
line-number = "relative"

[editor.file-picker]
hidden = false

[keys.insert]
"tab" = "normal_mode"

[keys.select]
"tab" = "normal_mode"